Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,12 +1,26 @@
 name: Main workflow
 on: push
+env: # Set the secret as an input
+  github_username: ${{ github.actor }}
+  github_password: ${{ secrets.GITHUB_TOKEN }} # Must be made available to the workflow
+  GIT_COMMIT: ${{ github.sha }}
 jobs:
   Build:
     runs-on: ubuntu-latest
     container: gradle:6-jdk11
     steps:
+      - name: Validate GitHub username is all lowercase
+        id: validate_lower
+        run: |
+          if [[ "${{ env.github_username }}" =~ [A-Z] ]]; then
+            echo "::error::Validation Failed: GitHub username '${{ env.github_username }}' cannot contain uppercase characters."
+            exit 1
+          else
+            echo "GitHub username format is valid."
+          fi
+        shell: bash
       - name: Clone down repository
-        uses: actions/checkout@v4       
+        uses: actions/checkout@v4
       - name: Build application
         run: ci/build-app.sh
       - name: Test
@@ -19,7 +33,8 @@ jobs:
           include-hidden-files: true
   Linting:
     runs-on: ubuntu-latest
-    needs: [Build]
+    needs: 
+        - Build
     steps:
       - name: Download code
         uses: actions/download-artifact@v4
@@ -32,31 +47,25 @@ jobs:
           DEFAULT_BRANCH: main
           # To report GitHub Actions status checks
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          DISABLE_ERRORS: true          
-  EditorConfig:
+          DISABLE_ERRORS: true      
+  Docker-image:
     runs-on: ubuntu-latest
+    needs: [Build]
+    permissions:
+      packages: write
     steps:
-      - uses: actions/checkout@v4
-      - uses: editorconfig-checker/action-editorconfig-checker@main
-      - run: editorconfig-checker
-  SonarQube:
-    runs-on: ubuntu-latest
-    needs: [Build] 
-    steps:
-    - name: checkout
-      uses: actions/checkout@v4
-
-    - name: setup node
-      uses: actions/setup-node@v4
-      with: 
-        node-version: 22
-
-    - name: SonarQubeScan
-      uses: sonarsource/sonarcloud-github-action@v4.0.0
-      env:
-        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-
-
+    - name: Download code
+      uses: actions/download-artifact@v4
+      with:
+        name: code
+        path: .
+    - name: ls
+      run: ls -la ci
+    - name: build docker
+      run: bash ci/build-docker.sh
+    - name: push docker
+      run: bash ci/push-docker.sh        
+  
 
 
 
